# Use a dedicated slim python base
FROM python:3.14-slim

# Install only the specific library needed
RUN pip install --no-cache-dir pyyaml==6.0.1

# Copy only the script
COPY dispatcher/dispatcher.py .

ENTRYPOINT ["python", "dispatcher.py"]
